<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'phpmailer\\phpmailer\\exception' => '/src/Exception.php',
                'phpmailer\\phpmailer\\oauth' => '/src/OAuth.php',
                'phpmailer\\phpmailer\\phpmailer' => '/src/PHPMailer.php',
                'phpmailer\\phpmailer\\pop3' => '/src/POP3.php',
                'phpmailer\\phpmailer\\smtp' => '/src/SMTP.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
